server {
    listen 80;
    server_name git.40.66.42.189.nip.io;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name git.40.66.42.189.nip.io;

    ssl_certificate /etc/letsencrypt/live/status.40.66.42.189.nip.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/status.40.66.42.189.nip.io/privkey.pem;

    location / {
        proxy_pass http://172.17.0.1:3002;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
}server {
    listen 80;
    server_name git.40.66.42.189.nip.io;

    location / {
        proxy_pass http://172.17.0.1:3002;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
}
