server {
    listen 80;
    server_name dash.40.66.42.189.nip.io;

    location / {
        proxy_pass http://172.17.0.1:8082;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
}
