services:
  it-tools:
    image: sharevb/it-tools:latest
    container_name: it-tools
    restart: unless-stopped
    ports:
      - "172.17.0.1:8091:8080"

    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://127.0.0.1:8080/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
