services:
  memos:
    image: neosmemo/memos:stable
    container_name: memos
    restart: unless-stopped
    ports:
      - "5230:5230"
    volumes:
      - memos_data:/var/opt/memos

volumes:
  memos_data:

networks:
  default:
    external: true
    name: nginx_default
